console.log(5)
console.log(12.7)
console.log(-123)

console.log(typeof 5)
console.log(typeof 12.7)
console.log(typeof -123)

console.log(2+2)
console.log(2*4 - 3)
console.log(8 / 4)
console.log(5 + (2*4))

console.log(Infinity)
console.log(-Infinity)
console.log(NaN)

console.log(typeof Infinity)
console.log(typeof -Infinity)
console.log(typeof NaN)

console.log(2+3)
console.log(5 - 12)
console.log(4 * 4)
console.log(5 / 3)
console.log(20 % 2)
console.log(21 % 2)
console.log(50 % 500)
console.log(20 / 9)
console.log(800 * 2)

console.log(typeof (2+3))
console.log(typeof (5 - 12))
console.log(typeof (4 * 4))
console.log(typeof (5 / 3))
console.log(typeof (20 % 2))
console.log(typeof (21 % 2))
console.log(typeof (50 % 500))
console.log(typeof (20 / 9))
console.log(typeof (800 * 2))